// =============================================================================
// Server-Side Menu Export Templates Definition
// Contains 22+ meticulously designed styles across backgrounds, font palettes,
// border schemes, logo outlines, and layout paradigms.
// =============================================================================

export interface MenuTemplateThemeConfig {
  pageBg: string;               // PDF background color
  cardBg: string;               // Category bar / item background
  cardBorderColor: string;      // Category border outline
  frameColor: string;           // Outer page decorative frame
  innerFrameColor?: string;     // Inner fine hairline frame
  logoBorderColor: string;      // Outline color for centered logo
  logoBgColor: string;          // Background circle for logo
  textPrimary: string;          // Main title, category name, dish name, price
  textSecondary: string;        // Branch details, descriptions, notes
  textAccent: string;           // Taglines, badges, special accents
  dividerColor: string;         // Line dividers between items
  headerBannerStyle: 'solid-card' | 'outlined-card' | 'underlined' | 'vintage-ornate' | 'modern-pill';
  fontFamilyHeader: 'Helvetica-Bold' | 'Times-Bold' | 'Courier-Bold';
  fontFamilyBody: 'Helvetica' | 'Times-Roman' | 'Courier';
  fontFamilyItalic: 'Helvetica-Oblique' | 'Times-Italic' | 'Courier-Oblique';
  foodTypeColors: {
    veg: string;
    nonVeg: string;
    egg: string;
    vegan: string;
  };
}

export interface MenuTemplate {
  id: string;
  name: string;
  subtitle: string;
  category: 'dark' | 'light' | 'vintage' | 'luxury' | 'modern';
  layoutStyle: 'centered' | 'classic-boxed' | 'ornate-vintage' | 'modern-minimal' | 'two-column-look';
  badge: string;
  themeConfig: MenuTemplateThemeConfig;
  previewColors: {
    bg: string;
    card: string;
    text: string;
    accent: string;
    border: string;
  };
}

export const MENU_TEMPLATES: MenuTemplate[] = [
  // ── 1. Charcoal Noir (Default) ──────────────────────────────────────────────
  {
    id: 'charcoal-noir',
    name: 'Charcoal Noir',
    subtitle: 'Deep charcoal background with pure white typography & amber accents',
    category: 'dark',
    layoutStyle: 'centered',
    badge: 'Popular',
    previewColors: {
      bg: '#121214',
      card: '#1c1c21',
      text: '#ffffff',
      accent: '#f59e0b',
      border: '#ffffff',
    },
    themeConfig: {
      pageBg: '#121214',
      cardBg: '#1c1c21',
      cardBorderColor: '#ffffff',
      frameColor: '#27272a',
      innerFrameColor: '#18181b',
      logoBorderColor: '#ffffff',
      logoBgColor: '#18181b',
      textPrimary: '#ffffff',
      textSecondary: '#94a3b8',
      textAccent: '#f59e0b',
      dividerColor: '#27272a',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#22c55e',
        nonVeg: '#ef4444',
        egg: '#f59e0b',
        vegan: '#10b981',
      },
    },
  },

  // ── 2. Midnight Velvet & Gold ───────────────────────────────────────────────
  {
    id: 'midnight-gold',
    name: 'Midnight Velvet & 24K Gold',
    subtitle: 'Opulent navy dusk with warm champagne gold borders & accents',
    category: 'luxury',
    layoutStyle: 'centered',
    badge: 'Luxury',
    previewColors: {
      bg: '#0a0e1a',
      card: '#12182b',
      text: '#fbf7ee',
      accent: '#dfb15b',
      border: '#dfb15b',
    },
    themeConfig: {
      pageBg: '#0a0e1a',
      cardBg: '#12182b',
      cardBorderColor: '#dfb15b',
      frameColor: '#dfb15b',
      innerFrameColor: '#253257',
      logoBorderColor: '#dfb15b',
      logoBgColor: '#12182b',
      textPrimary: '#fbf7ee',
      textSecondary: '#cbd5e1',
      textAccent: '#dfb15b',
      dividerColor: '#1e293b',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#34d399',
        nonVeg: '#f87171',
        egg: '#fbbf24',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 3. Royal Emerald Bistro ────────────────────────────────────────────────
  {
    id: 'royal-emerald',
    name: 'Royal Emerald Bistro',
    subtitle: 'Deep forest botanical green with crisp pearl & mint accents',
    category: 'dark',
    layoutStyle: 'centered',
    badge: 'Bistro',
    previewColors: {
      bg: '#0c2419',
      card: '#133928',
      text: '#f0fdf4',
      accent: '#34d399',
      border: '#34d399',
    },
    themeConfig: {
      pageBg: '#0c2419',
      cardBg: '#133928',
      cardBorderColor: '#34d399',
      frameColor: '#1b4d36',
      innerFrameColor: '#0a1d14',
      logoBorderColor: '#ffffff',
      logoBgColor: '#133928',
      textPrimary: '#f0fdf4',
      textSecondary: '#a7f3d0',
      textAccent: '#fbbf24',
      dividerColor: '#194933',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#4ade80',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 4. Bordeaux Grand Reserve (Vintage Wine) ───────────────────────────────
  {
    id: 'burgundy-vintage',
    name: 'Bordeaux & Grand Reserve',
    subtitle: 'Deep vintage wine burgundy with warm cream typography & classic serif',
    category: 'vintage',
    layoutStyle: 'ornate-vintage',
    badge: 'Vintage',
    previewColors: {
      bg: '#250a14',
      card: '#381220',
      text: '#fef3c7',
      accent: '#f59e0b',
      border: '#e2b755',
    },
    themeConfig: {
      pageBg: '#250a14',
      cardBg: '#381220',
      cardBorderColor: '#e2b755',
      frameColor: '#e2b755',
      innerFrameColor: '#4f1a2e',
      logoBorderColor: '#e2b755',
      logoBgColor: '#381220',
      textPrimary: '#fef3c7',
      textSecondary: '#fde68a',
      textAccent: '#e2b755',
      dividerColor: '#4f1a2e',
      headerBannerStyle: 'vintage-ornate',
      fontFamilyHeader: 'Times-Bold',
      fontFamilyBody: 'Times-Roman',
      fontFamilyItalic: 'Times-Italic',
      foodTypeColors: {
        veg: '#86efac',
        nonVeg: '#fca5a5',
        egg: '#fde047',
        vegan: '#5eead4',
      },
    },
  },

  // ── 5. Minimalist Chalk White ──────────────────────────────────────────────
  {
    id: 'minimalist-chalk',
    name: 'Minimalist Chalk White',
    subtitle: 'Stark pure white background with crisp modern dark slate typography',
    category: 'light',
    layoutStyle: 'modern-minimal',
    badge: 'Clean',
    previewColors: {
      bg: '#ffffff',
      card: '#f8fafc',
      text: '#0f172a',
      accent: '#2563eb',
      border: '#0f172a',
    },
    themeConfig: {
      pageBg: '#ffffff',
      cardBg: '#f8fafc',
      cardBorderColor: '#0f172a',
      frameColor: '#e2e8f0',
      innerFrameColor: '#f1f5f9',
      logoBorderColor: '#0f172a',
      logoBgColor: '#f8fafc',
      textPrimary: '#0f172a',
      textSecondary: '#64748b',
      textAccent: '#2563eb',
      dividerColor: '#e2e8f0',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#16a34a',
        nonVeg: '#dc2626',
        egg: '#d97706',
        vegan: '#0d9488',
      },
    },
  },

  // ── 6. Tuscan Antique Parchment ────────────────────────────────────────────
  {
    id: 'parchment-heritage',
    name: 'Tuscan Antique Parchment',
    subtitle: 'Warm textured parchment with rich sepia espresso & double ornate lines',
    category: 'vintage',
    layoutStyle: 'ornate-vintage',
    badge: 'Heritage',
    previewColors: {
      bg: '#fcf8f0',
      card: '#f4ede0',
      text: '#2c1810',
      accent: '#a0522d',
      border: '#8b5a2b',
    },
    themeConfig: {
      pageBg: '#fcf8f0',
      cardBg: '#f4ede0',
      cardBorderColor: '#8b5a2b',
      frameColor: '#8b5a2b',
      innerFrameColor: '#dcc7b0',
      logoBorderColor: '#8b5a2b',
      logoBgColor: '#f4ede0',
      textPrimary: '#2c1810',
      textSecondary: '#6b4c3e',
      textAccent: '#a0522d',
      dividerColor: '#dcc7b0',
      headerBannerStyle: 'vintage-ornate',
      fontFamilyHeader: 'Times-Bold',
      fontFamilyBody: 'Times-Roman',
      fontFamilyItalic: 'Times-Italic',
      foodTypeColors: {
        veg: '#2e7d32',
        nonVeg: '#c62828',
        egg: '#ef6c00',
        vegan: '#00796b',
      },
    },
  },

  // ── 7. Tokyo Cyber Slate ───────────────────────────────────────────────────
  {
    id: 'tokyo-slate-cyber',
    name: 'Tokyo Cyber Slate',
    subtitle: 'Deep titanium slate with electric cyan headers and high-contrast lines',
    category: 'dark',
    layoutStyle: 'modern-minimal',
    badge: 'Modern',
    previewColors: {
      bg: '#0f172a',
      card: '#1e293b',
      text: '#ffffff',
      accent: '#38bdf8',
      border: '#38bdf8',
    },
    themeConfig: {
      pageBg: '#0f172a',
      cardBg: '#1e293b',
      cardBorderColor: '#38bdf8',
      frameColor: '#334155',
      innerFrameColor: '#1e293b',
      logoBorderColor: '#38bdf8',
      logoBgColor: '#1e293b',
      textPrimary: '#ffffff',
      textSecondary: '#94a3b8',
      textAccent: '#38bdf8',
      dividerColor: '#334155',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#22c55e',
        nonVeg: '#f43f5e',
        egg: '#facc15',
        vegan: '#06b6d4',
      },
    },
  },

  // ── 8. Mediterranean Azure Blue ───────────────────────────────────────────
  {
    id: 'mediterranean-azure',
    name: 'Mediterranean Azure',
    subtitle: 'Deep Aegean ocean blue with pure white typography & sun gold highlights',
    category: 'dark',
    layoutStyle: 'centered',
    badge: 'Seafood/Grill',
    previewColors: {
      bg: '#0c1e3d',
      card: '#132b54',
      text: '#ffffff',
      accent: '#38bdf8',
      border: '#ffffff',
    },
    themeConfig: {
      pageBg: '#0c1e3d',
      cardBg: '#132b54',
      cardBorderColor: '#ffffff',
      frameColor: '#1e40af',
      innerFrameColor: '#0a162d',
      logoBorderColor: '#ffffff',
      logoBgColor: '#132b54',
      textPrimary: '#ffffff',
      textSecondary: '#cbd5e1',
      textAccent: '#fbbf24',
      dividerColor: '#1e3a8a',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#34d399',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 9. Art Deco Onyx & Brass ───────────────────────────────────────────────
  {
    id: 'art-deco-onyx',
    name: 'Art Deco Onyx & Brass',
    subtitle: 'Sleek luxury onyx with geometric gold borders & Gatsby elegance',
    category: 'luxury',
    layoutStyle: 'classic-boxed',
    badge: 'Speakeasy',
    previewColors: {
      bg: '#18181b',
      card: '#27272a',
      text: '#ffffff',
      accent: '#d4af37',
      border: '#d4af37',
    },
    themeConfig: {
      pageBg: '#18181b',
      cardBg: '#27272a',
      cardBorderColor: '#d4af37',
      frameColor: '#d4af37',
      innerFrameColor: '#3f3f46',
      logoBorderColor: '#d4af37',
      logoBgColor: '#27272a',
      textPrimary: '#ffffff',
      textSecondary: '#d4d4d8',
      textAccent: '#d4af37',
      dividerColor: '#3f3f46',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#4ade80',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 10. Artisan Cafe Latte ─────────────────────────────────────────────────
  {
    id: 'cafe-latte-cream',
    name: 'Artisan Cafe Latte',
    subtitle: 'Warm frothy cream background with roasted espresso typography',
    category: 'light',
    layoutStyle: 'modern-minimal',
    badge: 'Cafe & Bakery',
    previewColors: {
      bg: '#f6f1eb',
      card: '#eae1d6',
      text: '#38220f',
      accent: '#a06138',
      border: '#6f4e37',
    },
    themeConfig: {
      pageBg: '#f6f1eb',
      cardBg: '#eae1d6',
      cardBorderColor: '#6f4e37',
      frameColor: '#d7c7b7',
      innerFrameColor: '#ede4d8',
      logoBorderColor: '#6f4e37',
      logoBgColor: '#eae1d6',
      textPrimary: '#38220f',
      textSecondary: '#6e4b30',
      textAccent: '#a06138',
      dividerColor: '#d7c7b7',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#2e7d32',
        nonVeg: '#b71c1c',
        egg: '#e65100',
        vegan: '#00695c',
      },
    },
  },

  // ── 11. Scandinavian Nordic Pine ───────────────────────────────────────────
  {
    id: 'nordic-pine',
    name: 'Nordic Pine & Alpine',
    subtitle: 'Dark Scandinavian pine green with ice frost white and sage accents',
    category: 'dark',
    layoutStyle: 'centered',
    badge: 'Nordic',
    previewColors: {
      bg: '#0f2017',
      card: '#163124',
      text: '#f8fafc',
      accent: '#4ade80',
      border: '#ffffff',
    },
    themeConfig: {
      pageBg: '#0f2017',
      cardBg: '#163124',
      cardBorderColor: '#ffffff',
      frameColor: '#234d38',
      innerFrameColor: '#0a1610',
      logoBorderColor: '#ffffff',
      logoBgColor: '#163124',
      textPrimary: '#f8fafc',
      textSecondary: '#bbf7d0',
      textAccent: '#4ade80',
      dividerColor: '#1f4431',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#4ade80',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 12. Obsidian & Crimson Ruby ────────────────────────────────────────────
  {
    id: 'gothic-obsidian',
    name: 'Obsidian & Crimson Ruby',
    subtitle: 'Jet black background with vivid scarlet red badges and white typography',
    category: 'dark',
    layoutStyle: 'classic-boxed',
    badge: 'Bold Dark',
    previewColors: {
      bg: '#0a0a0c',
      card: '#16161a',
      text: '#ffffff',
      accent: '#e11d48',
      border: '#e11d48',
    },
    themeConfig: {
      pageBg: '#0a0a0c',
      cardBg: '#16161a',
      cardBorderColor: '#e11d48',
      frameColor: '#27272a',
      innerFrameColor: '#121214',
      logoBorderColor: '#ffffff',
      logoBgColor: '#16161a',
      textPrimary: '#ffffff',
      textSecondary: '#cbd5e1',
      textAccent: '#e11d48',
      dividerColor: '#27272a',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#22c55e',
        nonVeg: '#ef4444',
        egg: '#f59e0b',
        vegan: '#10b981',
      },
    },
  },

  // ── 13. Craft Brewhouse Kraft ──────────────────────────────────────────────
  {
    id: 'rustic-kraft',
    name: 'Craft Brewhouse & Kraft',
    subtitle: 'Warm recycled kraft cardboard aesthetic with bold dark bronze type',
    category: 'vintage',
    layoutStyle: 'classic-boxed',
    badge: 'Craft Beer/Pub',
    previewColors: {
      bg: '#ecd9c1',
      card: '#dfc7ab',
      text: '#291e17',
      accent: '#b45309',
      border: '#291e17',
    },
    themeConfig: {
      pageBg: '#ecd9c1',
      cardBg: '#dfc7ab',
      cardBorderColor: '#291e17',
      frameColor: '#291e17',
      innerFrameColor: '#caa988',
      logoBorderColor: '#291e17',
      logoBgColor: '#dfc7ab',
      textPrimary: '#291e17',
      textSecondary: '#5a4234',
      textAccent: '#b45309',
      dividerColor: '#caa988',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#2e7d32',
        nonVeg: '#b71c1c',
        egg: '#e65100',
        vegan: '#00695c',
      },
    },
  },

  // ── 14. Swiss International Clean ──────────────────────────────────────────
  {
    id: 'swiss-monochrome',
    name: 'Swiss International Clean',
    subtitle: 'High-contrast stark monochrome with heavy modern headers & precision grid',
    category: 'modern',
    layoutStyle: 'modern-minimal',
    badge: 'Editorial',
    previewColors: {
      bg: '#ffffff',
      card: '#000000',
      text: '#000000',
      accent: '#000000',
      border: '#000000',
    },
    themeConfig: {
      pageBg: '#ffffff',
      cardBg: '#000000',
      cardBorderColor: '#000000',
      frameColor: '#000000',
      innerFrameColor: '#e5e5e5',
      logoBorderColor: '#000000',
      logoBgColor: '#ffffff',
      textPrimary: '#000000',
      textSecondary: '#525252',
      textAccent: '#000000',
      dividerColor: '#e5e5e5',
      headerBannerStyle: 'solid-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#15803d',
        nonVeg: '#b91c1c',
        egg: '#b45309',
        vegan: '#0f766e',
      },
    },
  },

  // ── 15. Havana Sunset Lounge ───────────────────────────────────────────────
  {
    id: 'sunset-havana',
    name: 'Havana Sunset Lounge',
    subtitle: 'Deep tropical twilight plum with coral pink & mango gold highlights',
    category: 'dark',
    layoutStyle: 'centered',
    badge: 'Cocktails/Tapas',
    previewColors: {
      bg: '#21161d',
      card: '#33212c',
      text: '#ffffff',
      accent: '#fb7185',
      border: '#ffffff',
    },
    themeConfig: {
      pageBg: '#21161d',
      cardBg: '#33212c',
      cardBorderColor: '#ffffff',
      frameColor: '#fb7185',
      innerFrameColor: '#47283b',
      logoBorderColor: '#ffffff',
      logoBgColor: '#33212c',
      textPrimary: '#ffffff',
      textSecondary: '#cbd5e1',
      textAccent: '#fb7185',
      dividerColor: '#47283b',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#34d399',
        nonVeg: '#fb7185',
        egg: '#facc15',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 16. Prime Steakhouse & Copper ──────────────────────────────────────────
  {
    id: 'steakhouse-copper',
    name: 'Prime Steakhouse & Copper',
    subtitle: 'Charred oak barrel black with burnished copper frames & cream text',
    category: 'luxury',
    layoutStyle: 'classic-boxed',
    badge: 'Steakhouse',
    previewColors: {
      bg: '#171311',
      card: '#271f1b',
      text: '#fef3c7',
      accent: '#c26d38',
      border: '#c26d38',
    },
    themeConfig: {
      pageBg: '#171311',
      cardBg: '#271f1b',
      cardBorderColor: '#c26d38',
      frameColor: '#c26d38',
      innerFrameColor: '#3d2e27',
      logoBorderColor: '#ffffff',
      logoBgColor: '#271f1b',
      textPrimary: '#fef3c7',
      textSecondary: '#d6c5b8',
      textAccent: '#c26d38',
      dividerColor: '#3d2e27',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#4ade80',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 17. Botanical Garden Sage ──────────────────────────────────────────────
  {
    id: 'botanical-sage',
    name: 'Botanical Garden Sage',
    subtitle: 'Soft herbal linen background with deep moss green botanical type',
    category: 'light',
    layoutStyle: 'modern-minimal',
    badge: 'Organic / Vegan',
    previewColors: {
      bg: '#f3f6f1',
      card: '#e4ece0',
      text: '#193822',
      accent: '#2f663f',
      border: '#193822',
    },
    themeConfig: {
      pageBg: '#f3f6f1',
      cardBg: '#e4ece0',
      cardBorderColor: '#193822',
      frameColor: '#8ca893',
      innerFrameColor: '#e0e9df',
      logoBorderColor: '#193822',
      logoBgColor: '#e4ece0',
      textPrimary: '#193822',
      textSecondary: '#425a48',
      textAccent: '#2f663f',
      dividerColor: '#d0ddd0',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#2e7d32',
        nonVeg: '#c62828',
        egg: '#ef6c00',
        vegan: '#00796b',
      },
    },
  },

  // ── 18. Imperial Sapphire Palace ───────────────────────────────────────────
  {
    id: 'royal-sapphire',
    name: 'Imperial Sapphire Palace',
    subtitle: 'Regal dark sapphire blue with diamond white & golden crest typography',
    category: 'luxury',
    layoutStyle: 'centered',
    badge: 'Fine Dining',
    previewColors: {
      bg: '#081026',
      card: '#101d42',
      text: '#ffffff',
      accent: '#f59e0b',
      border: '#ffffff',
    },
    themeConfig: {
      pageBg: '#081026',
      cardBg: '#101d42',
      cardBorderColor: '#ffffff',
      frameColor: '#f59e0b',
      innerFrameColor: '#1c2f66',
      logoBorderColor: '#ffffff',
      logoBgColor: '#101d42',
      textPrimary: '#ffffff',
      textSecondary: '#cbd5e1',
      textAccent: '#f59e0b',
      dividerColor: '#1c2f66',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#34d399',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 19. Urban Streetfood Graphite ──────────────────────────────────────────
  {
    id: 'urban-graphite',
    name: 'Urban Streetfood Graphite',
    subtitle: 'Dark graphite with high-voltage street yellow accents & punchy layout',
    category: 'modern',
    layoutStyle: 'centered',
    badge: 'Street Food',
    previewColors: {
      bg: '#1c1f24',
      card: '#292d34',
      text: '#ffffff',
      accent: '#facc15',
      border: '#facc15',
    },
    themeConfig: {
      pageBg: '#1c1f24',
      cardBg: '#292d34',
      cardBorderColor: '#facc15',
      frameColor: '#3d444f',
      innerFrameColor: '#16181c',
      logoBorderColor: '#ffffff',
      logoBgColor: '#292d34',
      textPrimary: '#ffffff',
      textSecondary: '#cbd5e1',
      textAccent: '#facc15',
      dividerColor: '#3d444f',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#22c55e',
        nonVeg: '#ef4444',
        egg: '#facc15',
        vegan: '#10b981',
      },
    },
  },

  // ── 20. Italian Espresso Macchiato ─────────────────────────────────────────
  {
    id: 'espresso-macchiato',
    name: 'Italian Espresso Macchiato',
    subtitle: 'Deep roasted espresso bean with warm foam crema text & gold piping',
    category: 'luxury',
    layoutStyle: 'centered',
    badge: 'Italian / Pizzeria',
    previewColors: {
      bg: '#1a110a',
      card: '#2c1e13',
      text: '#fdfbf7',
      accent: '#dfb15b',
      border: '#ffffff',
    },
    themeConfig: {
      pageBg: '#1a110a',
      cardBg: '#2c1e13',
      cardBorderColor: '#ffffff',
      frameColor: '#dfb15b',
      innerFrameColor: '#3d2b1c',
      logoBorderColor: '#ffffff',
      logoBgColor: '#2c1e13',
      textPrimary: '#fdfbf7',
      textSecondary: '#d8c7b8',
      textAccent: '#dfb15b',
      dividerColor: '#3d2b1c',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#4ade80',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 21. Rose Gold & Velvet Dusk ────────────────────────────────────────────
  {
    id: 'rose-gold-noir',
    name: 'Rose Gold & Velvet Dusk',
    subtitle: 'Silky dusk charcoal with shimmering metallic rose gold borders',
    category: 'luxury',
    layoutStyle: 'centered',
    badge: 'Chic / Lounge',
    previewColors: {
      bg: '#18151c',
      card: '#26202d',
      text: '#ffffff',
      accent: '#e0a899',
      border: '#e0a899',
    },
    themeConfig: {
      pageBg: '#18151c',
      cardBg: '#26202d',
      cardBorderColor: '#e0a899',
      frameColor: '#e0a899',
      innerFrameColor: '#3a2f45',
      logoBorderColor: '#ffffff',
      logoBgColor: '#26202d',
      textPrimary: '#ffffff',
      textSecondary: '#cbd5e1',
      textAccent: '#e0a899',
      dividerColor: '#3a2f45',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#34d399',
        nonVeg: '#f87171',
        egg: '#fde047',
        vegan: '#2dd4bf',
      },
    },
  },

  // ── 22. Kyoto Zen Bamboo & Riverstone ──────────────────────────────────────
  {
    id: 'zen-bamboo-stone',
    name: 'Kyoto Zen Bamboo',
    subtitle: 'Dark river stone slate with fresh matcha green outlines and rice paper white',
    category: 'dark',
    layoutStyle: 'modern-minimal',
    badge: 'Japanese / Asian',
    previewColors: {
      bg: '#141816',
      card: '#1d2421',
      text: '#ffffff',
      accent: '#22c55e',
      border: '#ffffff',
    },
    themeConfig: {
      pageBg: '#141816',
      cardBg: '#1d2421',
      cardBorderColor: '#ffffff',
      frameColor: '#22c55e',
      innerFrameColor: '#293530',
      logoBorderColor: '#ffffff',
      logoBgColor: '#1d2421',
      textPrimary: '#ffffff',
      textSecondary: '#cbd5e1',
      textAccent: '#22c55e',
      dividerColor: '#293530',
      headerBannerStyle: 'outlined-card',
      fontFamilyHeader: 'Helvetica-Bold',
      fontFamilyBody: 'Helvetica',
      fontFamilyItalic: 'Helvetica-Oblique',
      foodTypeColors: {
        veg: '#22c55e',
        nonVeg: '#f43f5e',
        egg: '#facc15',
        vegan: '#10b981',
      },
    },
  },
];

export function getMenuTemplateById(templateId?: string): MenuTemplate {
  if (!templateId) return MENU_TEMPLATES[0];
  const found = MENU_TEMPLATES.find((t) => t.id === templateId.toLowerCase().trim());
  return found || MENU_TEMPLATES[0];
}
